CREATE TABLE IF NOT EXISTS import_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(32) NOT NULL,
    uploaded_file_count INT NOT NULL DEFAULT 0,
    longterm_row_count INT NOT NULL DEFAULT 0,
    spot_row_count INT NOT NULL DEFAULT 0,
    failed_file_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    created_by VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    normalized_at TIMESTAMP NULL,
    confirmed_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS import_job_files (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    data_type VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    normalized_rows INT NOT NULL DEFAULT 0,
    skipped_rows INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_job_files_job_id (job_id),
    CONSTRAINT fk_import_job_files_job FOREIGN KEY (job_id) REFERENCES import_jobs(id)
);

CREATE TABLE IF NOT EXISTS import_job_longterm_rows (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    transaction_id INT NULL,
    company_id BIGINT NOT NULL,
    place VARCHAR(100) NULL,
    transaction_date DATE NULL,
    transaction_name VARCHAR(255) NULL,
    transaction_type_id INT NULL,
    outsend_province VARCHAR(50) NULL,
    gen_type_id INT NOT NULL,
    transaction_period_id INT NULL,
    transaction_start_year INT NULL,
    transaction_end_year INT NULL,
    contract_start_date DATE NULL,
    contract_end_date DATE NULL,
    is_green BOOLEAN NOT NULL DEFAULT FALSE,
    is_cheap BOOLEAN NOT NULL DEFAULT FALSE,
    base_price DECIMAL(18,4) NULL,
    market_size DECIMAL(18,6) NULL,
    market_participation_capacity DECIMAL(18,4) NULL,
    market_avg_price DECIMAL(18,4) NULL,
    chng_participation_capacity DECIMAL(18,4) NULL,
    chng_transaction_amount DECIMAL(18,6) NULL,
    chng_avg_price DECIMAL(18,4) NULL,
    env_premium DECIMAL(18,4) NULL,
    data_source VARCHAR(255) NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_job_longterm_rows_job_id (job_id)
);

CREATE TABLE IF NOT EXISTS import_job_spot_rows (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL,
    date DATE NOT NULL,
    gen_type_id INT NOT NULL,
    gen_amount DECIMAL(18,6) NULL,
    longterm_amount DECIMAL(18,6) NULL,
    longterm_price DECIMAL(18,4) NULL,
    longterm_percent DECIMAL(5,4) NULL,
    spot_price DECIMAL(18,4) NULL,
    chng_spot_price DECIMAL(18,4) NULL,
    data_source VARCHAR(255) NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_job_spot_rows_job_id (job_id)
);

CREATE TABLE IF NOT EXISTS import_versions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version_code VARCHAR(64) NOT NULL UNIQUE,
    source_job_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    longterm_row_count INT NOT NULL DEFAULT 0,
    spot_row_count INT NOT NULL DEFAULT 0,
    created_by VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMP NULL,
    rolled_back_at TIMESTAMP NULL,
    remark VARCHAR(500) NULL,
    INDEX idx_import_versions_status (status)
);

CREATE TABLE IF NOT EXISTS import_version_longterm_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version_id BIGINT NOT NULL,
    transaction_id INT NULL,
    company_id BIGINT NOT NULL,
    place VARCHAR(100) NULL,
    transaction_date DATE NULL,
    transaction_name VARCHAR(255) NULL,
    transaction_type_id INT NULL,
    outsend_province VARCHAR(50) NULL,
    gen_type_id INT NOT NULL,
    transaction_period_id INT NULL,
    transaction_start_year INT NULL,
    transaction_end_year INT NULL,
    contract_start_date DATE NULL,
    contract_end_date DATE NULL,
    is_green BOOLEAN NOT NULL DEFAULT FALSE,
    is_cheap BOOLEAN NOT NULL DEFAULT FALSE,
    base_price DECIMAL(18,4) NULL,
    market_size DECIMAL(18,6) NULL,
    market_participation_capacity DECIMAL(18,4) NULL,
    market_avg_price DECIMAL(18,4) NULL,
    chng_participation_capacity DECIMAL(18,4) NULL,
    chng_transaction_amount DECIMAL(18,6) NULL,
    chng_avg_price DECIMAL(18,4) NULL,
    env_premium DECIMAL(18,4) NULL,
    data_source VARCHAR(255) NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_version_longterm_snapshot_version_id (version_id)
);

CREATE TABLE IF NOT EXISTS import_version_spot_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    date DATE NOT NULL,
    gen_type_id INT NOT NULL,
    gen_amount DECIMAL(18,6) NULL,
    longterm_amount DECIMAL(18,6) NULL,
    longterm_price DECIMAL(18,4) NULL,
    longterm_percent DECIMAL(5,4) NULL,
    spot_price DECIMAL(18,4) NULL,
    chng_spot_price DECIMAL(18,4) NULL,
    data_source VARCHAR(255) NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_version_spot_snapshot_version_id (version_id)
);

CREATE TABLE IF NOT EXISTS import_restore_points (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_type VARCHAR(32) NOT NULL,
    trigger_action VARCHAR(32) NOT NULL,
    reference_job_id BIGINT NULL,
    reference_version_id BIGINT NULL,
    from_version_id BIGINT NULL,
    to_version_id BIGINT NULL,
    binlog_file VARCHAR(255) NOT NULL,
    binlog_position BIGINT NOT NULL,
    gtid_set TEXT NULL,
    operator_name VARCHAR(64) NULL,
    note VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_restore_points_created_at (created_at),
    INDEX idx_import_restore_points_action (trigger_action),
    INDEX idx_import_restore_points_to_version (to_version_id)
);
